server:
    port: 9094
logging:
    level: DEBUG
    file: logs/log.log
spring:
  profiles:
    active: loc
#ip报警
ip:
  address: /home/hbc/appspider
  toMail: caichengzhang@hbc315.com
#geo平台
geo:
  url: http://114.113.66.37/xiaojinku/api/sendDataToKafka
  pwd: reptile#!170213*$
auth:
  pwd: 123qweasdZXC
